


WITH cte AS ( SELECT CHAT_ID, USER_NAME, EMPLOYEE_ID, CHAT_START, CHAT_END, FIRST_INTERACTION, LAST_INTERACTION, LEAD(FIRST_INTERACTION) OVER (ORDER BY CHAT_START) AS NEXT_FIRST_INTERACTION FROM TB_TECH_SUPPORT_CHAT_CONSULT ORDER BY CHAT_START ) 
SELECT CHAT_ID, USER_NAME, EMPLOYEE_ID, CHAT_START, CHAT_END, FIRST_INTERACTION, LAST_INTERACTION, CASE WHEN NEXT_FIRST_INTERACTION IS NOT NULL AND FIRST_INTERACTION > NEXT_FIRST_INTERACTION THEN 'Delayed' ELSE NULL END AS QUEUE_JUMP_STATUS FROM cte;
